### ISSUE TITLE
Build issue, apparently due to removal of 1.12.0 from repository-estatio.forge.cloudbees.com

### ISSUE THREAD

**Issue by jttkim** [isisaddons/isis-app-todoapp#9] opened 2016-05-14 12:38 UTC
Following README.md, I cloned the git repo but `mvn clean install` ran into trouble because a maven repo doesn't resolve. Specifically, I get

```
$ mvn -U clean
[INFO] Scanning for projects...
Downloading: http://repository-estatio.forge.cloudbees.com/snapshot/org/apache/isis/core/isis/1.12.0-SNAPSHOT/maven-metadata.xml
Downloading: https://repository.apache.org/content/repositories/snapshots/org/apache/isis/core/isis/1.12.0-SNAPSHOT/maven-metadata.xml
Downloading: https://repository.apache.org/content/repositories/snapshots/org/apache/isis/core/isis/1.12.0-SNAPSHOT/isis-1.12.0-SNAPSHOT.pom
Downloading: http://repository-estatio.forge.cloudbees.com/snapshot/org/apache/isis/core/isis/1.12.0-SNAPSHOT/isis-1.12.0-SNAPSHOT.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not find artifact org.apache.isis.core:isis:pom:1.12.0-SNAPSHOT in apache.snapshots (https://repository.apache.org/content/repositories/snapshots/) @ line 272, column 25
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.isisaddons.app:todoapp:1.12.0-SNAPSHOT (/home/jtk/hacking/java/isis/isis-app-todoapp/pom.xml) has 1 error
[ERROR]     Non-resolvable import POM: Could not find artifact org.apache.isis.core:isis:pom:1.12.0-SNAPSHOT in apache.snapshots (https://repository.apache.org/content/repositories/snapshots/) @ line 272, column 25 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
```

Pasting 
`http://repository-estatio.forge.cloudbees.com/snapshot/org/apache/isis/core/isis/1.12.0-SNAPSHOT/isis-1.12.0-SNAPSHOT.pom` into my browser's URL input field gives a 404 error, and working upwards to `http://repository-estatio.forge.cloudbees.com/snapshot/org/apache/isis/core/isis/` reveals that there's only `1.13.0-SNAPSHOT`, i.e. no 1.12 anymore.

So I tried changing the Isis version in the top-level `pom.xml` to

```
<isis.version>1.13.0-SNAPSHOT</isis.version>
```

(in the `properties` element). With this change, `mvn -U clean` runs successfully, but then alas

```
$ mvn -U install
[INFO] Scanning for projects...

[... many messages of successful downloads etc. snipped...]

[WARNING] The POM for org.apache.isis.tool:isis-maven-plugin:jar:1.13.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Isis Addons ToDoApp ................................ SUCCESS [  0.381 s]
[INFO] Isis Addons ToDoApp DOM ............................ SUCCESS [  8.196 s]
[INFO] Isis Addons ToDoApp Fixtures ....................... SUCCESS [  0.090 s]
[INFO] Isis Addons ToDoApp App ............................ SUCCESS [  2.039 s]
[INFO] Isis Addons ToDoApp XSD ............................ FAILURE [  0.004 s]
[INFO] Isis Addons ToDoApp Integration Tests .............. SKIPPED
[INFO] Isis Addons ToDoApp Webapp ......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

So neither 1.12.0 nor 1.13.0 work. Sorry I can only report this, not offer a solution / pull request -- this is my first look at Isis.

Best regards, Jan

**Comment by jwgmeligmeyling** [comment] 2016-05-24 21:51
I believe I have the same issue. 

On master:

```
[WARNING] The POM for org.apache.isis.tool:isis-maven-plugin:jar:1.13.0-SNAPSHOT is missing, no dependency information available
```

At `01b6a8d`:

```
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not find artifact org.apache.isis.core:isis:pom:1.12.0-SNAPSHOT in apache.snapshots (https://repository.apache.org/content/repositories/snapshots/) @ line 272, column 25
 @ 
```

**Comment by danhaywood** [comment] 2016-06-01 08:15
1.13.0-SNAPSHOT is now stable again, so am closing.  thx

**Closed as completed by danhaywood** 2016-06-01 08:15 UTC

**Comment by kjeldahl** [comment] 2016-06-29 07:13
It seems to still be a problem. Travis cannot build: https://travis-ci.org/isisaddons/isis-app-todoapp/builds/138061287 and I get the same error locally.

**Comment by nagendratest** [comment] 2016-07-11 13:44
Please advice me how can i resolve this issue

[INFO] Isis Addons ToDoApp ................................ SUCCESS [  0.335 s]
[INFO] Isis Addons ToDoApp DOM ............................ SUCCESS [ 11.156 s]
[INFO] Isis Addons ToDoApp Fixtures ....................... SUCCESS [  1.466 s]
[INFO] Isis Addons ToDoApp App ............................ SUCCESS [  2.844 s]
[INFO] Isis Addons ToDoApp XSD ............................ FAILURE [  0.023 s]
[INFO] Isis Addons ToDoApp Integration Tests .............. SKIPPED
[INFO] Isis Addons ToDoApp Webapp ......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.421 s
[INFO] Finished at: 2016-07-11T19:13:17+05:30
[INFO] Final Memory: 44M/435M
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.apache.isis.tool:isis-maven-plugin:1.13.0-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.apache.isis.tool:isis-maven-plugin:jar:1.13.0-SNAPSHOT -> [Help 1]
org.apache.maven.plugin.PluginResolutionException: Plugin org.apache.isis.tool:isis-maven-plugin:1.13.0-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.apache.isis.tool:isis-maven-plugin:jar:1.13.0-SNAPSHOT
        at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:128)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getPluginDescriptor(DefaultMavenPluginManager.java:179)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getMojoDescriptor(DefaultMavenPluginManager.java:284)
        at org.apache.maven.plugin.DefaultBuildPluginManager.getMojoDescriptor(DefaultBuildPluginManager.java:241)
        at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.setupMojoExecution(DefaultLifecycleExecutionPlanCalculator.java:169)
        at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.setupMojoExecutions(DefaultLifecycleExecutionPlanCalculator.java:155)
        at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateExecutionPlan(DefaultLifecycleExecutionPlanCalculator.java:131)
        at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateExecutionPlan(DefaultLifecycleExecutionPlanCalculator.java:145)
        at org.apache.maven.lifecycle.internal.builder.BuilderCommon.resolveBuildPlan(BuilderCommon.java:96)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:109)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.apache.isis.tool:isis-maven-plugin:jar:1.13.0-SNAPSHOT
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294)
        at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:124)
        ... 26 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.apache.isis.tool:isis-maven-plugin:jar:1.13.0-SNAPSHOT
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:434)
        ... 30 more

**Comment by danhaywood** [comment] 2016-07-14 11:51
I've just bumped the todoapp to use Isis v1.13.0, so try it again.  thx.

**Comment by jorgefdzg** [comment] 2019-03-19 21:55
I had the same issue....
`Downloading from estatio.snapshots: http://repository-estatio.forge.cloudbees.com/snapshot/org/isisaddons/module/settings/isis-module-settings-dom/1.13.0-SNAPSHOT/maven-metadata.xml
Downloading from snapshots-repo: http://repository-estatio.forge.cloudbees.com/snapshot/org/isisaddons/module/settings/isis-module-settings-dom/1.13.0-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata org.isisaddons.module.settings:isis-module-settings-dom:1.13.0-SNAPSHOT/maven-metadata.xml from/to estatio.snapshots (http://repository-estatio.forge.cloudbees.com/snapshot/): repository-estatio.forge.cloudbees.com
[WARNING] Could not transfer metadata org.isisaddons.module.settings:isis-module-settings-dom:1.13.0-SNAPSHOT/maven-metadata.xml from/to snapshots-repo (http://repository-estatio.forge.cloudbees.com/snapshot/): repository-estatio.forge.cloudbees.com
[WARNING] Failure to transfer org.isisaddons.module.settings:isis-module-settings-dom:1.13.0-SNAPSHOT/maven-metadata.xml from http://repository-estatio.forge.cloudbees.com/snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of estatio.snapshots has elapsed or updates are forced. Original error: Could not transfer metadata org.isisaddons.module.settings:isis-module-settings-dom:1.13.0-SNAPSHOT/maven-metadata.xml from/to estatio.snapshots (http://repository-estatio.forge.cloudbees.com/snapshot/): repository-estatio.forge.cloudbees.com
[WARNING] Failure to transfer org.isisaddons.module.settings:isis-module-settings-dom:1.13.0-SNAPSHOT/maven-metadata.xml from http://repository-estatio.forge.cloudbees.com/snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of snapshots-repo has elapsed or updates are forced. Original error: Could not transfer metadata org.isisaddons.module.settings:isis-module-settings-dom:1.13.0-SNAPSHOT/maven-metadata.xml from/to snapshots-repo (http://repository-estatio.forge.cloudbees.com/snapshot/): repository-estatio.forge.cloudbees.com
Downloading from estatio.snapshots: http://repository-estatio.forge.cloudbees.com/snapshot/org/isisaddons/module/settings/isis-module-settings-dom/1.13.0-SNAPSHOT/isis-module-settings-dom-1.13.0-SNAPSHOT.pom
Downloading from snapshots-repo: http://repository-estatio.forge.cloudbees.com/snapshot/org/isisaddons/module/settings/isis-module-settings-dom/1.13.0-SNAPSHOT/isis-module-settings-dom-1.13.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for App ToDoApp 1.14.0-SNAPSHOT:
[INFO]
[INFO] App ToDoApp ........................................ SUCCESS [  0.658 s]
[INFO] App ToDoApp DOM .................................... SUCCESS [ 13.511 s]
[INFO] App ToDoApp Fixtures ............................... SUCCESS [  2.151 s]
[INFO] App ToDoApp App .................................... SUCCESS [  6.534 s]
[INFO] App ToDoApp XSD .................................... FAILURE [  1.618 s]
[INFO] App ToDoApp Integration Tests ...................... SKIPPED
[INFO] App ToDoApp Webapp ................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  24.792 s
[INFO] Finished at: 2019-03-19T14:19:49-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.isis.tool:isis-maven-plugin:1.13.0:xsd (default) on project todoapp-xsd: Execution default of goal org.apache.isis.tool:isis-maven-plugin:1.13.0:xsd failed: Plugin org.apache.isis.tool:isis-maven-plugin:1.13.0 or one of its dependencies could not be resolved: Failed to collect dependencies at org.apache.isis.tool:isis-maven-plugin:jar:1.13.0 -> org.isisaddons.app:todoapp-app:jar:1.14.0-SNAPSHOT -> org.isisaddons.module.togglz:isis-module-togglz-glue:jar:1.13.0 -> org.isisaddons.module.settings:isis-module-settings-dom:jar:1.13.0-SNAPSHOT: Failed to read artifact descriptor for org.isisaddons.module.settings:isis-module-settings-dom:jar:1.13.0-SNAPSHOT: Could not transfer artifact org.isisaddons.module.settings:isis-module-settings-dom:pom:1.13.0-SNAPSHOT from/to estatio.snapshots (http://repository-estatio.forge.cloudbees.com/snapshot/): repository-estatio.forge.cloudbees.com: Unknown host repository-estatio.forge.cloudbees.com -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :todoapp-xsd
`

**Comment by guntutur** [comment] 2019-04-24 16:53
i had exact same issue on building todoapp example provided

here are some message warning from maven build

> [WARNING] Could not transfer metadata org.isisaddons.module.settings:isis-module-settings-dom:1.13.0-SNAPSHOT/maven-metadata.xml from/to estatio.snapshots (http://repository-estatio.forge.cloudbees.com/snapshot/): repository-estatio.forge.cloudbees.com
> [WARNING] Could not transfer metadata org.isisaddons.module.settings:isis-module-settings-dom:1.13.0-SNAPSHOT/maven-metadata.xml from/to snapshots-repo (http://repository-estatio.forge.cloudbees.com/snapshot/): repository-estatio.forge.cloudbees.com
> [WARNING] Failure to transfer org.isisaddons.module.settings:isis-module-settings-dom:1.13.0-SNAPSHOT/maven-metadata.xml from http://repository-estatio.forge.cloudbees.com/snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of estatio.snapshots has elapsed or updates are forced. Original error: Could not transfer metadata org.isisaddons.module.settings:isis-module-settings-dom:1.13.0-SNAPSHOT/maven-metadata.xml from/to estatio.snapshots (http://repository-estatio.forge.cloudbees.com/snapshot/): repository-estatio.forge.cloudbees.com
> [WARNING] Failure to transfer org.isisaddons.module.settings:isis-module-settings-dom:1.13.0-SNAPSHOT/maven-metadata.xml from http://repository-estatio.forge.cloudbees.com/snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of snapshots-repo has elapsed or updates are forced. Original error: Could not transfer metadata org.isisaddons.module.settings:isis-module-settings-dom:1.13.0-SNAPSHOT/maven-metadata.xml from/to snapshots-repo (http://repository-estatio.forge.cloudbees.com/snapshot/): repository-estatio.forge.cloudbees.com

> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary:
> [INFO] 
> [INFO] App ToDoApp ........................................ SUCCESS [  1.885 s]
> [INFO] App ToDoApp DOM .................................... SUCCESS [06:40 min]
> [INFO] App ToDoApp Fixtures ............................... SUCCESS [  0.637 s]
> [INFO] App ToDoApp App .................................... SUCCESS [04:34 min]
> [INFO] App ToDoApp XSD .................................... FAILURE [ 41.833 s]
> [INFO] App ToDoApp Integration Tests ...................... SKIPPED
> [INFO] App ToDoApp Webapp ................................. SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------

does anyone have pointer on how to solve this?

**Comment by guntutur** [comment] 2019-04-24 16:56
the `http://repository-estatio.forge.cloudbees.com/` seems to be inaccessible, whats your suggestion on this @danhaywood ?

**Comment by sathiya-dev** [comment] 2019-05-21 07:40
> the `http://repository-estatio.forge.cloudbees.com/` seems to be inaccessible, whats your suggestion on this @danhaywood ?

I am facing the same issue. Any update on how we can fix this? @danhaywood

**Comment by newthings4learning** [comment] 2020-03-23 18:03
I am facing the same issue when I took the latest version from git repo:

`Could not transfer artifact org.isisaddons.module.settings:isis-module-settings-dom:pom:1.13.0-SNAPSHOT from/to estatio.snapshots (http://repository-estatio.forge.cloudbees.com/snapshot/): repository-estatio.forge.cloudbees.com` 

`Failed to execute goal org.apache.isis.tool:isis-maven-plugin:1.13.0:xsd (default) on project todoapp-xsd: Execution default of goal org.apache.isis.tool:isis-maven-plugin:1.13.0:xsd failed: Plugin org.apache.isis.tool:isis-maven-plugin:1.13.0 or one of its dependencies could not be resolved: Failed to collect dependencies at org.apache.isis.tool:isis-maven-plugin:jar:1.13.0 -> org.isisaddons.app:todoapp-app:jar:1.14.0-SNAPSHOT -> org.isisaddons.module.togglz:isis-module-togglz-glue:jar:1.13.0 -> org.isisaddons.module.settings:isis-module-settings-dom:jar:1.13.0-SNAPSHOT`


any suggestions please ?
